In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

In [5]:
import pandas as pd
from io import StringIO

csv_data = """order_id,product_id,quantity
1,P01,2
1,P05,1
2,P10,3
2,P02,2
3,P07,1
3,P03,4
4,P12,2
4,P08,1
5,P20,5
6,P15,3
7,P08,2
8,P11,1
9,P06,4
10,P09,2
11,P02,3
12,P04,2
13,P14,1
14,P18,2
15,P01,5
16,P07,3
17,P03,2
18,P12,4
19,P05,1
20,P10,2
21,P06,3
22,P08,2
23,P11,4
24,P02,1
25,P07,5
26,P09,2
27,P03,3
28,P14,2
29,P18,1
30,P01,4
31,P05,2
32,P10,3
33,P02,2
34,P07,1
35,P03,4
36,P12,2
37,P08,1
38,P20,5
39,P15,3
40,P08,2
41,P11,1
42,P06,4
43,P09,2
44,P02,3
45,P04,2
46,P14,1
47,P18,2
48,P01,5
49,P07,3
50,P03,2
51,P12,4
52,P05,1
53,P10,2
54,P06,3
55,P08,2
56,P11,4
57,P02,1
58,P07,5
59,P09,2
60,P03,3
61,P14,2
62,P18,1
63,P01,4
64,P05,2
65,P10,3
66,P02,2
67,P07,1
68,P03,4
69,P12,2
70,P08,1
71,P20,5
72,P15,3
73,P08,2
74,P11,1
75,P06,4
76,P09,2
77,P02,3
78,P04,2
79,P14,1
80,P18,2
81,P01,5
82,P07,3
83,P03,2
84,P12,4
85,P05,1
86,P10,2
87,P06,3
88,P08,2
89,P11,4
90,P02,1
91,P07,5
92,P09,2
93,P03,3
94,P14,2
95,P18,1
96,P01,4
97,P05,2
98,P10,3
99,P02,2
100,P07,1
"""

df_orders = pd.read_csv(StringIO(csv_data))
df_orders.head()

   order_id product_id  quantity
0         1        P01         2
1         1        P05         1
2         2        P10         3
3         2        P02         2
4         3        P07         1

In [6]:
import random

products = []
for i in range(50):
    products.append({
        "product_id": f"P{i+1:02}",
        "x": random.randint(0, 100),
        "y": random.randint(0, 100),
        "category": random.choice(["A","B","C"])
    })

df_products = pd.DataFrame(products)
df_products.to_csv("products.csv", index=False)

df_products.head()

  product_id   x   y category
0        P01  66  70        C
1        P02  72  33        B
2        P03  16  19        B
3        P04  38  83        B
4        P05  20  10        B

In [7]:
df_orders.to_csv("orders.csv", index=False)